stages:
  - checkstyle
  - test

image:                             parity/rust-builder:latest

.only:                             &only
  only:
    - /^integrate_gitlab-ci/

checkstyle-linux-stable:
  stage:                           checkstyle
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  allow_failure: true
  <<:                             *only
  tags:
    - linux-docker

test-linux-stable:
  stage:                           test
  script:
    - time cargo build --all
    - time cargo test --all
  <<:                             *only
  tags:
    - linux-docker

test-windows-stable:
  stage:                           test
  script:
    - cargo build --all
    - cargo test --all
  <<:                             *only
  tags:
    - rust-windows

test-mac-stable:
  stage:                           test
  script:
    - time cargo build --all
    - time cargo test --all
  <<:                             *only
  tags:
    - rust-mac
