stages:
  - checkstyle
  - test

image:                             parity/rust-builder:latest

checkstyle-linux-stable:
  stage:                           checkstyle
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  allow_failure: true
  only:
    - /^integrate_gitlab-ci/
  except:
    - master
  tags:
    - linux-docker

test-linux-stable:
  stage:                           test
  script:
    - time cargo build --all
    - time cargo test --all
  only:
    - /^integrate_gitlab-ci/
  except:
    - master
  tags:
    - linux-docker

test-windows-stable:
  stage:                           test
  script:
    - cargo build --all
    - cargo test --all
  only:
    - /^integrate_gitlab-ci/
  except:
    - master
  tags:
    - rust-windows

test-mac-stable:
  stage:                           test
  script:
    - time cargo build --all
    - time cargo test --all
  only:
    - /^integrate_gitlab-ci/
  except:
    - master
  tags:
    - rust-mac
