[package]
name = "jsonrpc-derive"
version = "10.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT"
documentation = "https://paritytech.github.io/jsonrpc/jsonrpc_derive/index.html"
repository = "https://github.com/paritytech/jsonrpc"
homepage = "https://github.com/paritytech/jsonrpc"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.15.22", features = ["full", "extra-traits", "visit", "fold"] }
proc-macro2 = "0.4"
quote = "0.6"

[dev-dependencies]
jsonrpc-core = { version = "10.0", path = "../core" }
jsonrpc-pubsub = { version = "10.0", path = "../pubsub" }
jsonrpc-tcp-server = { version = "10.0", path = "../tcp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
compiletest_rs = { version = "*", features = ["stable"] }
