[package]
authors = ["Parity Technologies <admin@parity.io>"]
documentation = "https://docs.rs/jsonrpc-derive/"
description = "High level, typed wrapper for `jsonrpc-core`"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-derive"
repository = "https://github.com/paritytech/jsonrpc"
version = "10.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.15.22", features = ["full", "extra-traits", "visit", "fold"] }
proc-macro2 = "0.4"
quote = "0.6"
proc-macro-crate = "0.1.3"

[dev-dependencies]
jsonrpc-core = { version = "10.1", path = "../core" }
jsonrpc-pubsub = { version = "10.1", path = "../pubsub" }
jsonrpc-tcp-server = { version = "10.1", path = "../tcp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
compiletest_rs = { version = "0.3", features = ["stable"] }
