[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "WebSockets server for JSON-RPC"
documentation = "https://docs.rs/jsonrpc-ws-server/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-ws-server"
repository = "https://github.com/paritytech/jsonrpc"
version = "10.1.0"

[dependencies]
jsonrpc-core = { version = "10.1", path = "../core" }
jsonrpc-server-utils = { version = "10.1", path = "../server-utils" }
log = "0.4"
parking_lot = "0.7"
slab = "0.4"
ws = "0.8"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
