[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "WebSockets server for JSON-RPC"
documentation = "https://docs.rs/jsonrpc-ws-server/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-ws-server"
repository = "https://github.com/paritytech/jsonrpc"
version = "14.2.0"

[dependencies]
futures01 = { version = "0.1", package = "futures" }
futures03 = { version = "0.3", package = "futures" }
jsonrpc-core = { version = "14.2", path = "../core" }
jsonrpc-server-utils = { version = "14.2", path = "../server-utils" }
log = "0.4"
parking_lot = "0.10.0"
slab = "0.4"
ws = "0.9"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
