[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "TCP/IP server for JSON-RPC"
documentation = "https://docs.rs/jsonrpc-tcp-server/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-tcp-server"
repository = "https://github.com/paritytech/jsonrpc"
version = "15.0.0"

[dependencies]
futures01 = { version = "0.1", package = "futures" }
# TODO remove when we no longer need compat (use jsonrpc-core re-export instead)
futures03 = { version = "0.3", features = ["compat"], package = "futures" }
jsonrpc-core = { version = "15.0", path = "../core" }
jsonrpc-server-utils = { version = "15.0", path = "../server-utils" }
log = "0.4"
parking_lot = "0.10.0"
tokio-service = "0.1"

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.7"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
