[package]
name = "jsonrpc-ipc-server"
description = "IPC server for JSON-RPC"
version = "7.0.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_ipc_server/index.html"

[dependencies]
jsonrpc-core = { version = "7.0", path = "../core" }
jsonrpc-server-utils = { version = "7.0", path = "../server-utils" }
log = "0.3"
parity-tokio-ipc = { git = "https://github.com/nikvolf/parity-tokio-ipc" }
tokio-service = "0.1"
tokio-uds = "0.1"

[dev-dependencies]
env_logger = "0.4"
lazy_static = "0.2"
